- name: Add required base packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
     - wget
     - curl
     - haveged
- name: Add yum if Centos
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
     - yum-plugin-priorities
  when: ansible_distribution == 'CentOS' 
