- name: Add EPEL repo
  yum:
    name: epel-release
    state: latest

- name: Add LUX repository
  yum_repository:
    name: lux
    description: LUX YUM repo
    baseurl: http://repo.iotti.biz/CentOS/$releasever
